name: ci

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Build ISO
        run: |
          pacman-key --init
          pacman-key --populate
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel archiso git
          mkdir -p work out
          mkarchiso -v -w work_dir -o out_dir .
          rm -rf work
          md5sum out_dir/*
      - uses: actions/upload-artifact@v4
        with:
          name: archiso
          path: out_dir/

